services:
  notificationservice.api:
    image: ${DOCKER_REGISTRY-}notificationserviceapi
    build:
      context: .
      dockerfile: NotificationService.API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"


  redis:
   image: redis:alpine
   ports:
    - "6379:6379"
   volumes:
    - ./data/redis:/data

  mssql:
   image: mcr.microsoft.com/mssql/server:2022-latest
   user: root
   ports:
    - "1433:1433"
   volumes:
    - ./data/mssql:/var/opt/mssql/data
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=MyStrong@Passw0rd
    - MSSQL_PID=Developer
