services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    container_name: userservice
    secrets:
      - jwt_private_key
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__Topics__EmailConfirmation=email-confirmation    
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081" 
    networks:
      - app-net
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
secrets:
   jwt_private_key:
    file: ./UserService.API/secrets/jwt_private_key.txt
    


    